### PR TITLE
DuckDB uses a simplified version of libpg_query

### PR DESCRIPTION
**Pull request by hannes**

### CODE REVIEW

**Comment by lfittl** [comment]
@hannesmuehleisen Sorry for the late response here, happy to see you're using it!

When you say "simplified" - is there a way we could keep a common branch, to make your work to rebase on new Postgres versions easier?

**Comment by hannes** [comment]
We made a lot of changes, including Windows support and exception handling **without** `setjmp` and friends, memory management, error handling etc. Also greatly simplified the header zoo that PG produced. I am not sure how easy it is to update this with newer `libpg_query` releases. Code is here: https://github.com/cwida/duckdb/tree/master/third_party/libpg_query

**Comment by lfittl** [comment]
@hannesmuehleisen This looks great!

I think you are correct that this might be difficult to unify. However, this is a great example of why the parser needs to be accessible outside of Postgres.

Did you make any modifications to the parser logic itself (e.g. to support custom syntax), or is the grammar/keywords/etc still the same?

**Comment by hannes** [comment]
Grammar and keywords are unchanged

**Pull request merged**
