### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gonzazoid**
I had already written my own wrapper for Node before I found that there is similar project. If you add this information it would be great.

### CODE REVIEW

**Comment by lfittl** [comment]
@gonzazoid Good catch, and sorry this wasn't more obvious. Merged!

I'm curious - what are you building using the Postgres parser in Node?

**Comment by gonzazoid** [comment]
> Good catch, and sorry this wasn't more obvious. Merged!

Never mind! Thank you ever so much!

> I'm curious - what are you building using the Postgres parser in Node?

It will be (I hope) a type generator for Typescript. It will generate types based on sql function's signatures and tables definitions and generate whole client to access to db (similar code for client side to access to API based on swagger's spec's already written and work). Also I hope to write diff-like module to compare sql expressions based on AST, it would be more useful than bare diff with line-based comparing (as part of migration toolchain).

**Comment by lfittl** [comment]
@gonzazoid Neat, that sounds like an impressive project, if you can make it work :-)

Let me know how it goes, happy to help with any questions you have regarding the parse tree format, or any other things you run into!

**Comment by gonzazoid** [comment]
> if you can make it work :-)

Hope, hope, hope!!! :)

Thank you for your kind words and support!

**Pull request merged**
