### PR TITLE
Upgrade to Postgres 17

### PR DESCRIPTION
**Pull request by msepga**
Noteworthy commits that change the build/test system:

- [Add support for abstract nodes in generator scripts](https://github.com/pganalyze/libpg_query/pull/264/commits/32210e74e83d32c571f5fcff5ae6fb2205a7fdeb)
  - Postgres 17 adds `JsonTablePlan*`, an abstract sub-type of `Node*`
- [Add `disableOnMsvc` option to fingerprint test generator](https://github.com/pganalyze/libpg_query/pull/264/commits/7138d8143c87b7722da55da7fa2907f25e7b8291) 
  - In #233, we disabled one of the tests for MSVC, but regenerating the fingerprint tests source removed this guard. This commit adds it as part of the generator.
-  [Ignore name_location in deparse tests](https://github.com/pganalyze/libpg_query/pull/264/commits/ee00566e4477f7f6c2b81b2c7be3e5681c9523fe)
    - New nodes in Postgres 17 include `name_location`, a type that needs to be cleared in deparse tests just like `location`.

### CODE REVIEW

**Comment by lelit** [comment]
Hi, I'm quite slowly trying to upgrade my `pglast` tool to this branch, having some problem here and there with the new _abstract_ nodes, but I'm confident I'll get there.

One of the first failing tests is a worrisome _segmentation fault_: the test simply exercises the protobuf parse/deparse entry points (ie, it just calls `pg_query_parse_protobuf()` and then `pg_query_deparse_protobuf()`, with very little massaging on the pglast side), passing a trivial query such as `SELECT 1`.

So I morphed your `examples/simple.c` into the following `deparse.c`:

``` c
// Welcome to the easiest way to parse an SQL query :-)
// Compile the file like this:
//
// cc -I../ -L../ deparse.c -lpg_query

#include <pg_query.h>
#include <stdio.h>
#include <stdlib.h>

size_t testCount = 6;
const char* tests[] = {
  "SELECT 1",
  "SELECT * FROM x WHERE z = 2",
  "SELECT 5.41414",
  "SELECT $1",
  "SELECT 999999999999999999999::numeric/1000000000000000000000",
  "SELECT 4790999999999999999999999999999999999999999999999999999999999999999999999999999999999999 * 9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999"
};

int main() {
  PgQueryProtobufParseResult result;
  size_t i;

  for (i = 0; i < testCount; i++) {
    result = pg_query_parse_protobuf(tests[i]);

    if (result.error) {
      printf("error: %s at %d of query %s\n",
             result.error->message,
             result.error->cursorpos,
             tests[i]);
    } else {
      PgQueryDeparseResult deparse_result = pg_query_deparse_protobuf(result.parse_tree);
      if (deparse_result.error) {
        printf("\nERROR for \"%s\"\n  %s\n",
               tests[i],
               deparse_result.error->message);
        pg_query_free_deparse_result(deparse_result);
      } else {
        printf("\n%s --> %s\n",
               tests[i],
               deparse_result.query);
        pg_query_free_deparse_result(deparse_result);
      }
    }

    pg_query_free_protobuf_parse_result(result);
  }

  pg_query_exit();

  return 0;
}
```

And it fails in the same way:

```
Program received signal SIGSEGV, Segmentation fault.
0x000055555559f4ab in pg_query_protobuf_to_nodes (protobuf=...) at src/pg_query_readfuncs_protobuf.c:169
169		if (result->n_stmts > 0)
(gdb) bt
#0  0x000055555559f4ab in pg_query_protobuf_to_nodes (protobuf=...) at src/pg_query_readfuncs_protobuf.c:169
#1  0x000055555558e532 in pg_query_deparse_protobuf (parse_tree=...) at src/pg_query_deparse.c:19
#2  0x000055555558e171 in main ()
```

What am I missing here?

Thanks&bye.

**Comment by msepga** [comment]
Hi @lelit, thanks for the test!

I can't seem to reproduce this here. I've tried the example on macOS (M1 ARM chip) with both `DEBUG=1` and regular optimized builds, as well is in an x86_64 ubuntu VM.

Can you try running `make clean && make libpg_query.a` just to be sure it's not some kind leftover compiled object from a previous release, interfering with the test?

**Comment by lelit** [comment]
> Can you try running `make clean && make libpg_query.a` just to be sure it's not some kind leftover compiled object from a previous release, interfering with the test?

That fixed it indeed, thank you: didn't come to mind given that I was operating in a (evidently not enterely) fresh clone of pglast, of which libpg_query is a submodule!

**Review by lfittl — APPROVED** [review]
:+1:

Outstanding TODO:
- Add PL/pgSQL test for array types
- Update Makefile to copy PL/pgSQL regression tests automatically

**Pull request merged**
