### PR TITLE
Postgres 12 support

### PR DESCRIPTION
**Pull request by lfittl**
Please note that this is still work in progress.

**Note:** Once completed, this PR will be merged into the `12-latest` branch (not yet created)

## TODO (Required)

* [ ] Fingerprinting updates
* [ ] Memory leak tests
* [ ] Verification of downstream libraries
  * [x] pg_query_go
  * [x] pg_query (Ruby)
  * others
* [ ] Review/merge work in https://github.com/lfittl/libpg_query/pull/58
* [ ] Merge https://github.com/lfittl/libpg_query/tree/12-latest-develop-protobuf into this branch

## TODO (Nice to have)

* [ ] Cleanup `patches/01_parse_replacement_char.patch` patch so it applies cleanly
* [ ] Review `extract_source` analysis for failures (in particular JIT-related code doesn't work - we should explicitly exclude it)
* [ ] Review whether Postgres 12 brings any deparser improvements (see discussion in https://github.com/lfittl/libpg_query/pull/62 -- note the reason the Postgres deparser hasn't been used historically is because it requires catalog access to work)
* [ ] Fix building on Linux / ARM64
* [ ] Fix building on Windows

### CODE REVIEW

**Comment by pyramation** [comment]
@lfittl thank you for taking this on! It's great to see :) 

Excited to start running PG12!

Definitely +1 on the deparser, would allow us to remove an entire class of libraries that exist for deparsing, and we could use the real PG deparser! Either way, thanks for considering!

**Comment by bir** [comment]
@lfittl Any support you would like on this?  Happy to assist to get Postgres 12 support live.

**Comment by bir** [comment]
FYI - I have found this branch to be stable for my needs when using the JSON output.  I create a package for easily working with it here: https://github.com/gofoji/pgtree, including extensive unit tests validating the parser output.
The protobuf export fails for me.

**Comment by pyramation** [comment]
awesome @bir ! I also tested it out and got tests to work! The one test I did was a parsing a `CreateStmt` with a generated column since that was new in 12 and works great!

**Comment by bir** [comment]
@pyramation Yep, generated columns work great.  I added printer tests for them: https://github.com/gofoji/pgtree/blob/master/testdata/create_generated_want.sql
I have not run into a single parser issue.

**Comment by johanbrandhorst** [comment]
What's the status of this PR? Anything I can do to help?

**Comment by lfittl** [comment]
> What's the status of this PR? Anything I can do to help?

Latest work is at https://github.com/lfittl/libpg_query/tree/13-latest-develop-protobuf - there is some remaining items (and I'll be closing this PR soon & opening a new one with the TODO list), but overall trending well to finally get out a new release within the next weeks (with the Postgres 13 parser)

**Comment by pyramation** [comment]
awesome! super exciting 👍

**Comment by lfittl** [comment]
Superseded by #87

**Pull request closed without merging**
