### PR TITLE
Move deparser to dedicated file without pg_query dependencies

### LINKED ISSUE #180: Making query deparsing indepenently usable
I am using `libpg_query`'s deparsing functionality in [Omnigres](https://github.com/omnigres/omnigres/tree/master/extensions/omni_sql). However, since it's primarily a collection of extensions, the primary use case of libpg_query itself doesn't quite fit. I don't use it independently of Postgres, I am supplementing Postgres with the deparsing functionality when I need to manipulate or analyze queries.

I've done a fairly simple job integrating deparsing code (as seen above) but going forward, every time deparsing changes, I'd need to repeat a few steps, which is not ideal:

* Getting rid of pg_query_* API related stuff as it is not relevant
* Exposing `deparseRawStmt` function

I wonder if you'd be open to a patch that, for example, makes deparsing turn off pg_query_ and expose `deparseRawStmt` conditionally (perhaps opt-in to avoid the exposure of this throughout libpg_query itself)?

This way I can take the deparsing code and simply compile it with `-DISOLATED_PGQUERY_DEPARSING` and updating this dependency will be as simple as grabbing a new version of the file.

Happy to prepare a PR if this sounds like a good start.

### PR DESCRIPTION
**Pull request by yrashk**
This enables external projects that are interested to work with a raw parsetree to use the libpg_query deparser, without pulling in the main pg_query headers.

Fixes #180.

---

Supersedes #183

### CODE REVIEW

**Comment by lfittl** [comment]
@yrashk Sorry for the delay (last week got busier than expected with pgcon) -- if you could rebase this one more time (just merged a smaller change from https://github.com/pganalyze/libpg_query/pull/193 that was conflicting), I promise that we'll get this done now :)

**Comment by yrashk** [comment]
Rebased

**Comment by yrashk** [comment]
Bump

**Review by lfittl — APPROVED** [review]
:+1: Thanks for rebasing!

For future reference, here is the diff from the old `src/pg_query_deparse.c` to the new `src/postgres_deparse.c`:

```patch
lfittl@starfish libpg_query % git diff 15-latest:./src/pg_query_deparse.c ./src/postgres_deparse.c
diff --git a/src/pg_query_deparse.c b/src/postgres_deparse.c
index f37e5a0..8687a9d 100644
--- a/src/pg_query_deparse.c
+++ b/src/postgres_deparse.c
@@ -1,7 +1,4 @@
-#include "pg_query.h"
-#include "pg_query_internal.h"
-#include "pg_query_readfuncs.h"
-
+#include "postgres.h"
 #include "catalog/index.h"
 #include "catalog/pg_am.h"
 #include "catalog/pg_attribute.h"
@@ -141,7 +138,7 @@ static void deparseSelectStmt(StringInfo str, SelectStmt *stmt);
 static void deparseIntoClause(StringInfo str, IntoClause *into_clause);
 static void deparseRangeVar(StringInfo str, RangeVar *range_var, DeparseNodeContext context);
 static void deparseResTarget(StringInfo str, ResTarget *res_target, DeparseNodeContext context);
-static void deparseRawStmt(StringInfo str, RawStmt *raw_stmt);
+void deparseRawStmt(StringInfo str, RawStmt *raw_stmt);
 static void deparseAlias(StringInfo str, Alias *alias);
 static void deparseWindowDef(StringInfo str, WindowDef* window_def);
 static void deparseColumnRef(StringInfo str, ColumnRef* column_ref);
@@ -2380,11 +2377,11 @@ static void deparseRangeVar(StringInfo str, RangeVar *range_var, DeparseNodeCont
        removeTrailingSpace(str);
 }
 
-static void deparseRawStmt(StringInfo str, RawStmt *raw_stmt)
+void deparseRawStmt(StringInfo str, RawStmt *raw_stmt)
 {
        if (raw_stmt->stmt == NULL)
                elog(ERROR, "deparse error in deparseRawStmt: RawStmt with empty Stmt");
-       
+
        deparseStmt(str, raw_stmt->stmt);
 }
 
@@ -10648,62 +10645,3 @@ static void deparseStmt(StringInfo str, Node *node)
                        elog(ERROR, "deparse: unsupported top-level node type: %u", nodeTag(node));
        }
 }
-
-PgQueryDeparseResult pg_query_deparse_protobuf(PgQueryProtobuf parse_tree)
-{
-       PgQueryDeparseResult result = {0};
-       StringInfoData str;
-       MemoryContext ctx;
-       List *stmts;
-       ListCell *lc;
-
-       ctx = pg_query_enter_memory_context();
-
-       PG_TRY();
-       {
-               stmts = pg_query_protobuf_to_nodes(parse_tree);
-
-               initStringInfo(&str);
-
-               foreach(lc, stmts) {
-                       deparseRawStmt(&str, castNode(RawStmt, lfirst(lc)));
-                       if (lnext(stmts, lc))
-                               appendStringInfoString(&str, "; ");
-               }
-               result.query = strdup(str.data);
-       }
-       PG_CATCH();
-       {
-               ErrorData* error_data;
-               PgQueryError* error;
-
-               MemoryContextSwitchTo(ctx);
-               error_data = CopyErrorData();
-
-               // Note: This is intentionally malloc so exiting the memory context doesn't free this
-               error = malloc(sizeof(PgQueryError));
-               error->message   = strdup(error_data->message);
-               error->filename  = strdup(error_data->filename);
-               error->funcname  = strdup(error_data->funcname);
-               error->context   = NULL;
-               error->lineno   = error_data->lineno;
-               error->cursorpos = error_data->cursorpos;
-
-               result.error = error;
-               FlushErrorState();
-       }
-       PG_END_TRY();
-
-       pg_query_exit_memory_context(ctx);
-
-       return result;
-}
-
-void pg_query_free_deparse_result(PgQueryDeparseResult result)
-{
-       if (result.error) {
-               pg_query_free_error(result.error);
-       }
-
-       free(result.query);
-}
```

**Pull request merged**
